filebeat.autodiscover:
  providers:
    - type: docker
      #hints.enabled: true
      json.message_key: log  
      templates:
        - condition:
            equals:
              docker.container.labels.collect_logs: "true"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              json.keys_under_root: true
              #json.add_error_key: false
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~ 

output.logstash:
  hosts: ["logstash"]

