global:
  scrape_interval: 10s 

scrape_configs:
- job_name: kafka-metrics
  static_configs:
    - targets: ['broker:7071']
- job_name: burrow-exporter
  static_configs:
    - targets: ['burrow-exporter:8237']