apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  # - name: BurrowExporter
  #   type: prometheus
  #   access: proxy
  #   orgId: 1
  #   url: http://burrow-exporter:8237
  #   basicAuth: false
  #   isDefault: false
  #   editable: true